name: Build Firmware

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ath79-generic, ramips-mt7620]
      fail-fast: false

    env:
      IS_BUILDBOT: yes

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get --quiet --assume-yes --no-install-recommends --no-show-upgraded install git build-essential libncurses5-dev zlib1g-dev gawk time unzip libxml-perl flex wget gawk gettext quilt python libssl-dev
    - name: setup folders
      run: mkdir openwrt && ln -s ../logs openwrt/logs
    - name: configure build
      run: make -f Makefile.autobuild TARGET=${{matrix.target}} config
    - name: download openwrt packages
      run: make -f Makefile.autobuild -j$(nproc) TARGET=${{matrix.target}} download
    - name: build openwrt tools
      run: make -f Makefile.autobuild -j$(nproc) TARGET=${{matrix.target}} tools
    - name: build openwrt toolchain
      run: make -f Makefile.autobuild -j$(nproc) TARGET=${{matrix.target}} toolchain
    - name: build openwrt kmods
      run: make -f Makefile.autobuild -j$(nproc) TARGET=${{matrix.target}} kmods
    - name: build openwrt packages
      run: make -f Makefile.autobuild -j$(nproc) TARGET=${{matrix.target}} packages
    - name: build openwrt linux
      run: make -f Makefile.autobuild -j$(nproc) TARGET=${{matrix.target}} linux
    - name: build openwrt sdk
      run: make -f Makefile.autobuild -j$(nproc) TARGET=${{matrix.target}} sdk
    - name: build openwrt imagebuilder
      run: make -f Makefile.autobuild -j$(nproc) TARGET=${{matrix.target}} imagebuilder
    - name: build openwrt images
      run: make -f Makefile.autobuild -j$(nproc) TARGET=${{matrix.target}} images
    - name: Archive build logs
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v1
      with:
        name: ${{matrix.target}}_logs
        path: logs
    - name: Archive binaries
      if: ${{ !cancelled() }}
      continue-on-error: true
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.target }}_bins
        path: openwrt/bin/
