name: Build Firmware

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ath79-generic, ramips-mt7620]
      fail-fast: false

    env:
      IS_BUILDBOT: yes
      MAKE_OPTS: -j$(nproc) TARGET=${{matrix.target}}
      BUILD_LOG_DIR: logs

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get --quiet --assume-yes --no-install-recommends --no-show-upgraded install git build-essential libncurses5-dev zlib1g-dev gawk time unzip libxml-perl flex wget gawk gettext quilt python libssl-dev
    - name: setup folders
      run: mkdir logs
    - name: configure build
      run: make -f Makefile.autobuild ${MAKE_OPTS} config
    - name: OpenWrt-config to artifacts
      run: cp openwrt/.config logs/openwrt.config
    - name: download openwrt packages
      run: make -f Makefile.autobuild ${MAKE_OPTS} download
    - name: build openwrt tools
      run: make -f Makefile.autobuild ${MAKE_OPTS} tools
    - name: build openwrt toolchain
      run: make -f Makefile.autobuild ${MAKE_OPTS} toolchain
    - name: build openwrt kmods
      run: make -f Makefile.autobuild ${MAKE_OPTS} kmods
    - name: build openwrt packages
      run: make -f Makefile.autobuild ${MAKE_OPTS} packages
    - name: build openwrt linux
      run: make -f Makefile.autobuild ${MAKE_OPTS} linux
    - name: build openwrt sdk
      run: make -f Makefile.autobuild ${MAKE_OPTS} sdk
    - name: build openwrt imagebuilder
      run: make -f Makefile.autobuild ${MAKE_OPTS} imagebuilder
    - name: build openwrt images
      run: make -f Makefile.autobuild ${MAKE_OPTS} images
    - name: Archive build logs
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v1
      with:
        name: ${{matrix.target}}_logs
        path: logs
    - name: Archive binaries
      if: ${{ !cancelled() }}
      continue-on-error: true
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.target }}_bins
        path: openwrt/bin/
